FROM node:20-alpine AS build
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

ARG VITE_API_BASE_URL=http://localhost:5071/api
ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ARG VITE_REGISTRATION_ENABLED=true
ENV VITE_REGISTRATION_ENABLED=$VITE_REGISTRATION_ENABLED

RUN npm run build

FROM nginx:1.27-alpine AS final
WORKDIR /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist ./

EXPOSE 80
