import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react'

export type Language = 'hu' | 'en'

const STORAGE_KEY = 'asset-management-language'

const copy = {
  hu: {
    brandSubtitle: 'Eszközkezelő konzol',
    nav: {
      inventory: 'Eszközpark',
      users: 'Felhasználók',
      allCheckouts: 'Kikérési napló',
      myItems: 'Eszközeim',
      inventoryHint: 'Eszközök, állapotok és műveletek.',
      usersHint: 'Felhasználók és hozzárendelések.',
      allCheckoutsHint: 'Admin nézet az aktív hozzárendelésekhez és a lezárt előzményekhez.',
      myItemsHint: 'A nálad lévő eszközök és az előzmények.',
      login: 'Bejelentkezés',
      register: 'Regisztráció',
      activeSession: 'Aktív munkamenet',
      loggedIn: 'Bejelentkezve',
      accountMenu: 'Fiók',
      accountMenuHint: 'Profil és beállítások.',
      openUserMenu: 'Felhasználói menü megnyitása',
      closeUserMenu: 'Felhasználói menü bezárása',
      logout: 'Kilépés',
      profile: 'Profil',
      profileHint: 'A bejelentkezett felhasználó saját adatlapja.',
      settings: 'Beállítások',
      settingsHint: 'Nyelv és megjelenés.',
      language: 'Nyelv',
      theme: 'Megjelenés',
      lightMode: 'Világos',
      darkMode: 'Sötét',
    },
    auth: {
      loginKicker: 'Biztonságos hozzáférés',
      loginHeroTitle: 'Folytasd a munkát',
      loginHeroText:
        'Jelentkezz be, és nézd meg, mi van kiadva, mi elérhető, és mi igényel figyelmet.',
      registerKicker: 'Fiók létrehozása',
      registerHeroTitle: 'Kezdjük el',
      registerHeroText:
        'Hozz létre hozzáférést, hogy beléphess a rendszerbe és használhasd a saját nézeteidet.',
      highlightsInventoryTitle: 'Aktuális állapotok',
      highlightsInventoryText: 'Gyorsan látható, mi elérhető, mi kiadott, és mi van szervizben.',
      highlightsAdminTitle: 'Rendezett adatok',
      highlightsAdminText:
        'Az eszközök és a hozzárendelések ugyanabban a rendszerben követhetők.',
      highlightsTrackingTitle: 'Saját teendők',
      highlightsTrackingText: 'A saját eszközök, határidők és előzmények külön is megnyithatók.',
      registerHighlightsWorkspaceTitle: 'Egyértelmű felület',
      registerHighlightsWorkspaceText: 'Áttekinthető felület a napi munkához.',
      registerHighlightsNavTitle: 'Gyors elérés',
      registerHighlightsNavText: 'A fontos nézetek gyorsan elérhetők.',
      registerHighlightsFeedbackTitle: 'Egyértelmű visszajelzések',
      registerHighlightsFeedbackText:
        'A műveletek után világos állapotok és üzenetek segítenek.',
      welcomeBack: 'Üdv újra',
      createAccess: 'Új hozzáférés',
      loginTitle: 'Bejelentkezés',
      registerTitle: 'Regisztráció',
      loginText: 'Jelentkezz be, és folytasd ott, ahol abbahagytad az eszközkezelést.',
      registerText: 'Hozz létre új hozzáférést az eszközkezelő rendszerhez.',
      email: 'Email',
      password: 'Jelszó',
      name: 'Név',
      emailPlaceholder: 'nev@ceg.hu',
      passwordPlaceholder: '••••••••',
      minPasswordPlaceholder: 'Minimum 6 karakter',
      showPassword: 'Jelszó megjelenítése',
      hidePassword: 'Jelszó elrejtése',
      fullNamePlaceholder: 'Teljes név',
      loginSubmit: 'Belépés',
      loginSubmitting: 'Beléptetés...',
      loginError: 'Sikertelen bejelentkezés.',
      registerSubmit: 'Fiók létrehozása',
      registerSubmitting: 'Regisztrálás...',
      invalidEmail: 'Csak érvényes email címmel lehet regisztrálni.',
      registerError: 'Sikertelen regisztráció.',
      noAccount: 'Még nincs fiókod?',
      registerHere: 'Regisztrálj itt.',
      hasAccount: 'Már van fiókod?',
      loginHere: 'Lépj be innen.',
    },
    inventory: {
      heroKicker: 'Eszközáttekintés',
      heroTitle: 'Eszközpark',
      heroText:
        'A teljes eszközállomány és az aktuális állapotok.',
      signal: 'Összegzés',
      latestRecorded: 'Legutóbb rögzítve',
      noRecorded: 'Még nincs rögzített eszköz.',
      total: 'Összes eszköz',
      available: 'Elérhető',
      checkedOut: 'Kikérve',
      maintenance: 'Karbantartás alatt',
      totalNote: 'Teljes nyilvántartás',
      availableNote: 'Azonnal kiadható',
      checkedOutNote: 'Aktív használatban',
      maintenanceNote: 'Ideiglenesen zárolva',
      adminKicker: 'Admin felület',
      adminTitle: 'Új eszköz rögzítése',
      adminText:
        'Új céges eszköz rögzítése.',
      liveKicker: 'Nyilvántartás',
      liveTitle: 'Aktív eszközlista',
      liveText:
        'Az eszközök állapota, adatai és elérhető műveletei.',
      emptyTitle: 'Még nincs eszköz a rendszerben',
      emptyText:
        'Az első rögzített eszköz után itt jelenik meg az átlátható eszközlista.',
      createNamePlaceholder: 'Pl. MacBook Pro 16',
      createCategoryPlaceholder: 'Laptop, monitor, periféria',
      createSerialPlaceholder: 'SN-2026-001',
      createDescriptionPlaceholder: 'Rövid műszaki vagy üzemeltetési megjegyzés.',
      image: 'Kép',
      imageHint: 'JPG, PNG vagy WEBP, legfeljebb 2 MB.',
      imageSelect: 'Kép kiválasztása',
      imageReplace: 'Kép cseréje',
      imageRemove: 'Kép eltávolítása',
      imagePreview: 'Kép előnézet',
      imageInvalidType: 'Csak képfájl tölthető fel.',
      imageTooLarge: 'A kép legfeljebb 2 MB méretű lehet.',
      saveItem: 'Eszköz mentése',
      saving: 'Mentés...',
      details: 'Részletek',
      edit: 'Szerkesztés',
      delete: 'Törlés',
      deleting: 'Törlés...',
      makeMaintenance: 'Karbantartás',
      makeAvailable: 'Elérhetőre állít',
      compactDetails: 'Adatlap',
      compactEdit: 'Szerk.',
      compactDelete: 'Törlés',
      compactMaintenance: 'Szerviz',
      compactAvailable: 'Kész',
      assignee: 'Kezelő',
      checkedOutBy: 'Kikérte',
      maintenanceBy: 'Szervizbe küldte',
      actorUnknown: 'Ismeretlen felhasználó',
      listDescriptionFallback: 'Nincs leírás megadva.',
      editingKicker: 'Szerkesztés',
      editingTitle: 'Eszköz szerkesztése',
      editingText: 'Módosítsd az adatokat, majd mentsd a változásokat.',
      saveChanges: 'Változások mentése',
      cancel: 'Mégse',
      category: 'Kategória',
      recordedAt: 'Rögzítve',
      serial: 'Sorozatszám',
      description: 'Leírás',
      name: 'Név',
      createSuccess: 'Az eszköz sikeresen létrehozva.',
      createError: 'Nem sikerült létrehozni az eszközt.',
      updateSuccess: 'Az eszköz sikeresen frissítve.',
      updateError: 'Nem sikerült frissíteni az eszközt.',
      deleteSuccess: 'Az eszköz sikeresen törölve.',
      deleteError: 'Nem sikerült törölni az eszközt.',
      deleteConfirm: 'Biztosan törölni szeretnéd ezt az eszközt?',
      maintenanceSuccess: 'Az eszköz karbantartás alá helyezve.',
      maintenanceError: 'Nem sikerült karbantartás alá helyezni az eszközt.',
      availableSuccess: 'Az eszköz ismét elérhető.',
      availableError: 'Nem sikerült elérhetővé tenni az eszközt.',
      loadError: 'Nem sikerült betölteni az eszközöket.',
      loading: 'Eszközök betöltése...',
      searchPlaceholder: 'Keresés név, kategória vagy sorozatszám alapján',
      statusFilterLabel: 'Státusz',
      categoryFilterLabel: 'Kategória',
      sortByLabel: 'Rendezés',
      allStatuses: 'Minden státusz',
      allCategories: 'Minden kategória',
      sortByName: 'Név szerint',
      sortByNewest: 'Legújabbak elöl',
      sortByOldest: 'Legrégebbiek elöl',
      noResultsTitle: 'Nincs találat a megadott szűrőkre',
      noResultsText: 'Próbálj meg más keresést vagy lazább szűrést használni.',
    },
    checkouts: {
      heroKicker: 'Saját áttekintés',
      heroTitle: 'Saját kikérések',
      heroText:
        'Az aktív eszközök, határidők és lezárt visszahozások.',
      activeState: 'Aktuális helyzet',
      openCount: 'aktív tétel',
      overdueSummarySingle: '1 tétel határideje már lejárt.',
      overdueSummary: (count: number) => `${count} tétel határideje már lejárt.`,
      noOverdue: 'Jelenleg nincs lejárt kikérésed.',
      active: 'Aktív',
      overdue: 'Lejárt',
      closed: 'Lezárt',
      activeNote: 'Még nálad lévő eszközök',
      overdueNote: 'Azonnali figyelmet igényel',
      closedNote: 'Visszahozott tételek',
      emptyTitle: 'Még nincs kikérésed',
      emptyText:
        'Ha kikérsz egy eszközt, itt rögtön látni fogod a határidőt és az előzményeket.',
      checkedOutAt: 'Kikérve',
      dueAt: 'Határidő',
      returnedAt: 'Visszahozva',
      notClosed: 'Aktív',
      overdueBadge: 'Lejárt',
      overdueAlert: 'Ez a kikérés lejárt, az eszközt mielőbb vissza kell hozni.',
      dueSoonBadge: 'Közelgő határidő',
      dueSoonAlert: 'A határidő hamarosan lejár, érdemes előre tervezni a visszahozást.',
      note: 'Megjegyzés',
      equipmentPage: 'Adatlap',
      noNote: 'Nincs megjegyzés',
      loadError: 'Nem sikerült betölteni a kikéréseidet.',
      loading: 'Kikérések betöltése...',
      allHeroKicker: 'Kikérési napló',
      allHeroTitle: 'Kikérési események',
      allHeroText:
        'Az aktív hozzárendelések és a lezárt visszahozások.',
      allEmptyTitle: 'Még nincs egyetlen kikérés sem',
      allEmptyText:
        'Az első kikérés után itt jelennek meg az előzmények.',
      userHeroKicker: 'Felhasználó',
      userHeroText: (email: string) => `A kiválasztott felhasználó teljes kikérési előzménye: ${email}.`,
      userEmptyTitle: 'Ehhez a felhasználóhoz még nincs kikérés',
      userEmptyText: 'Az első hozzárendelés vagy kikérés után itt jelenik meg a teljes előzmény.',
      userLoadError: 'Nem sikerült betölteni a kiválasztott felhasználó kikéréseit.',
      userMissing: 'Hiányzó felhasználói azonosító.',
      userNotFound: 'A felhasználó nem található.',
      backToAll: 'Vissza az összes kikéréshez',
      searchPlaceholder: 'Keresés eszköz vagy sorozatszám alapján',
      allSearchPlaceholder: 'Keresés eszköz, sorozatszám vagy felhasználó alapján',
      statusFilterLabel: 'Állapot',
      sortByLabel: 'Rendezés',
      filterAll: 'Minden kikérés',
      filterActive: 'Aktívak',
      filterOverdue: 'Lejártak',
      filterClosed: 'Lezártak',
      sortRecent: 'Legfrissebbek elöl',
      sortDueSoon: 'Legközelebbi határidő',
      sortDueLate: 'Legtávolabbi határidő',
      noResultsTitle: 'Nincs találat a jelenlegi szűrőkre',
      noResultsText: 'Módosítsd a keresést vagy a kiválasztott szűrőket.',
    },
    myItems: {
      heroKicker: 'Saját oldal',
      heroTitle: 'Eszközeim',
      heroText:
        'A nálad lévő eszközök és a korábbi kikérések.',
      panelLabel: 'Aktív használat',
      panelValue: 'aktív eszköz',
      activeLabel: 'Nálad lévő eszközök',
      activeNote: 'Jelenleg hozzád rendelt vagy kikért eszközök',
      historyLabel: 'Előzmények',
      historyNote: 'Korábban lezárt kikérések és visszahozások',
      currentKicker: 'Aktív eszközök',
      currentTitle: 'Jelenleg nálad lévő eszközök',
      currentText: 'A jelenleg nálad lévő eszközök és a határidőik.',
      currentSearchPlaceholder: 'Keresés név, kategória vagy sorozatszám alapján',
      currentEmptyTitle: 'Jelenleg nincs nálad eszköz',
      currentEmptyText: 'Ha új eszközt kapsz vagy kikérsz valamit, itt fog megjelenni.',
      historyKicker: 'Előzmények',
      historyTitle: 'Korábbi kikérési előzmények',
      historyText: 'A lezárt és visszahozott tételek listája.',
      historySearchPlaceholder: 'Keresés a korábbi eszközök és megjegyzések között',
      historyEmptyTitle: 'Még nincs lezárt előzményed',
      historyEmptyText: 'A visszahozott eszközök később itt jelennek meg.',
    },
    users: {
      heroKicker: 'Felhasználók',
      heroTitle: 'Felhasználók',
      heroText: 'Felhasználók és a hozzájuk tartozó eszközök áttekintése.',
      panelLabel: 'Összegzés',
      panelValue: 'felhasználó',
      panelText: 'Kereshető, rendezhető lista a normál felhasználókról.',
      totalTracked: 'Összes kikérés',
      totalTrackedNote: 'Minden felhasználó összesített előzménye',
      activeTracked: 'Aktív kiosztások',
      activeTrackedNote: 'Jelenleg nyitott, vissza nem hozott eszközök',
      overdueTracked: 'Lejárt kiosztások',
      overdueTrackedNote: 'Azonnali figyelmet igénylő tételek',
      searchPlaceholder: 'Keresés név vagy email alapján',
      sortLabel: 'Rendezés',
      sortByName: 'Név szerint',
      sortByActivity: 'Aktív kiosztások szerint',
      emptyTitle: 'Még nincs felhasználó a rendszerben',
      emptyText: 'Az első normál felhasználó után itt megjelenik a teljes lista.',
      noResultsTitle: 'Nincs találat a keresésre',
      noResultsText: 'Próbálj meg más nevet vagy email címet keresni.',
      userLabel: 'Felhasználó',
      totalCheckoutsLabel: 'Összes kikérés',
      activeCheckoutsLabel: 'Aktív kikérések',
      overdueCheckoutsLabel: 'Lejárt kikérések',
      closedCheckoutsLabel: 'Lezárt kikérések',
      openOverview: 'Felhasználó megnyitása',
      backToUsers: 'Vissza a felhasználókhoz',
      detailHeroKicker: 'Felhasználói adatlap',
      detailHeroText: (email: string) =>
        `Az aktuális eszközök és az előzmények ennél a felhasználónál: ${email}.`,
      detailPanelValue: 'aktív eszköz',
      detailPanelText: 'Külön láthatók a jelenlegi eszközök és a lezárt előzmények.',
      currentItemsKicker: 'Jelenlegi eszközök',
      currentItemsTitle: 'Aktív hozzárendelt eszközök',
      currentItemsText: 'Azok az eszközök, amelyek most ennél a felhasználónál vannak.',
      currentSearchPlaceholder: 'Keresés a jelenlegi eszközök között',
      currentEmptyTitle: 'Jelenleg nincs nála aktív eszköz',
      currentEmptyText: 'Ha új eszközt rendelsz hozzá, itt fog megjelenni.',
      historyKicker: 'Előzmények',
      historyTitle: 'Lezárt kikérési előzmények',
      historyText: 'A visszahozott és lezárt kikérések listája.',
      historySearchPlaceholder: 'Keresés a lezárt előzmények között',
      historyEmptyTitle: 'Még nincs lezárt előzménye',
      historyEmptyText: 'Az első visszahozott eszköz után itt jelenik meg a history.',
      loadError: 'Nem sikerült betölteni a felhasználókat.',
      loading: 'Felhasználók betöltése...',
    },
    profile: {
      heroKicker: 'Profil',
      heroText: 'A bejelentkezett felhasználó alapadatai.',
      panelLabel: 'Szerepkör',
      nameLabel: 'Név',
      nameHint: 'A jelenlegi munkamenethez tartozó megjelenített név.',
      emailLabel: 'Email',
      emailHint: 'A bejelentkezéshez használt email cím.',
      roleLabel: 'Szerepkör',
      roleHint: 'Ez határozza meg, milyen nézeteket és műveleteket érsz el.',
      accountKicker: 'Fiókadatok',
      accountTitle: 'Alap adatok',
      accountText: 'Az aktuális bejelentkezett felhasználó adatai.',
      quickLinksKicker: 'Hivatkozások',
      quickLinksTitle: 'Gyors műveletek',
      quickLinksText: 'Gyors hivatkozások a fontos oldalakhoz.',
      primaryAdminAction: 'Felhasználók megnyitása',
      primaryUserAction: 'Eszközeim megnyitása',
      settingsAction: 'Beállítások megnyitása',
    },
    settings: {
      heroKicker: 'Beállítások',
      heroTitle: 'Megjelenés és nyelv',
      heroText: 'Az alkalmazás felületének beállításai.',
      panelLabel: 'Beállítások',
      panelValue: '2 lehetőség',
      panelText: 'Itt állítható a nyelv, és itt lesz a megjelenés is.',
      languageTitle: 'Nyelv',
      languageText: 'Válaszd ki, milyen nyelven jelenjen meg az alkalmazás felülete.',
      themeTitle: 'Megjelenés',
      themeText: 'A világos és sötét mód kapcsoló előkészítve látszik.',
    },
    details: {
      back: 'Vissza az eszközparkhoz',
      heroKicker: 'Eszközadatlap',
      heroText: 'Az eszköz adatai, állapota és előzményei.',
      recorded: 'Rögzítve',
      totalCheckouts: 'Összes kikérés',
      totalCheckoutsNote: 'Teljes használati előzmény',
      activeUser: 'Jelenlegi használó',
      free: 'Szabad',
      notIssued: 'Az eszköz jelenleg nincs kiadva.',
      deadlinePrefix: 'Határidő',
      dueSoonPrefix: 'Közelgő határidő',
      overduePrefix: 'Lejárt határidő',
      lastMovement: 'Utolsó mozgás',
      noHistory: 'Nincs',
      latestEvent: 'Legutóbbi esemény',
      noHistoryNote: 'Még nincs előzmény',
      title: 'Eszköz adatlap',
      subtitle: 'Főbb adatok és az aktuális üzemeltetési állapot.',
      category: 'Kategória',
      serial: 'Sorozatszám',
      createdAt: 'Létrehozva',
      description: 'Leírás',
      sendToMaintenance: 'Karbantartásra küldés',
      makeAvailable: 'Elérhetőre állít',
      checkoutKicker: 'Kikérés',
      checkoutTitle: 'Eszköz kikérése',
      checkoutText: 'Add meg a határidőt, és ha kell, egy rövid megjegyzést.',
      assignTitle: 'Eszköz hozzárendelése',
      assignText: 'Adminként egy kiválasztott felhasználóhoz rendelheted az eszközt.',
      assignUserLabel: 'Célfelhasználó',
      assignSubmit: 'Eszköz hozzárendelése',
      assignSuccess: 'Az eszköz sikeresen felhasználóhoz rendelve.',
      noAssignableUsers: 'Nincs elérhető felhasználó a hozzárendeléshez.',
      dueAt: 'Határidő',
      note: 'Megjegyzés',
      notePlaceholder: 'Opcionális megjegyzés',
      checkoutSubmit: 'Kikérem az eszközt',
      returnKicker: 'Visszavétel',
      returnTitle: 'Eszköz visszahozása',
      returnText: 'Zárd le a kikérést, és adj meg megjegyzést, ha szükséges.',
      returnSubmit: 'Visszahozom az eszközt',
      historyKicker: 'Előzmények',
      historyTitle: 'Kikérési előzmények',
      historyText: 'Az eszköz korábbi kikérései és visszahozásai.',
      noHistoryTitle: 'Még nincs előzmény',
      noHistoryText: 'Ehhez az eszközhöz még nem tartozik egyetlen kikérés sem.',
      active: 'Aktív',
      closed: 'Lezárt',
      summaryKicker: 'Gyors áttekintés',
      summaryTitle: 'Összefoglaló',
      status: 'Státusz',
      activeUserLabel: 'Aktív használó',
      unassigned: 'Nincs kiosztva',
      openUserHistory: 'Felhasználói adatlap',
      lastEvent: 'Utolsó esemény',
      usageKicker: 'Használati információk',
      usageTitle: 'Mire figyelj',
      issueability: 'Kiadhatóság',
      issueabilityYes: 'Azonnal kiadható',
      issueabilityNo: 'Jelenleg nem adható ki',
      returnability: 'Visszavétel állapota',
      returnabilityYes: 'A nyitott kikérés lezárható',
      returnabilityNo: 'Nincs nyitott kikérés',
      loadError: 'Nem sikerült betölteni az eszköz részleteit.',
      loading: 'Eszköz adatlap betöltése...',
      notFound: 'Az eszköz nem található.',
      missingId: 'Hiányzó eszközazonosító.',
      checkoutSuccess: 'Az eszköz sikeresen kikérve.',
      checkoutError: 'Nem sikerült kikérni az eszközt.',
      returnSuccess: 'Az eszköz sikeresen visszahozva.',
      returnError: 'Nem sikerült visszahozni az eszközt.',
      maintenanceSuccess: 'Az eszköz karbantartás alá helyezve.',
      maintenanceError: 'Nem sikerült karbantartás alá helyezni az eszközt.',
      availableSuccess: 'Az eszköz ismét elérhető.',
      availableError: 'Nem sikerült elérhetővé tenni az eszközt.',
    },
    common: {
      saveInProgress: 'Mentés...',
      unknownDate: 'Ismeretlen dátum',
      unknownDateTime: 'Ismeretlen időpont',
      me: 'Én',
      search: 'Keresés',
      view: 'Nézet',
      cardsView: 'Kártyák',
      listView: 'Lista',
      asset: 'Eszköz',
      image: 'Kép',
      category: 'Kategória',
      status: 'Státusz',
      user: 'Felhasználó',
      clearFilters: 'Szűrők törlése',
      actions: 'Műveletek',
      noImage: 'Nincs kép',
    },
  },
  en: {
    brandSubtitle: 'Operations Console',
    nav: {
      inventory: 'Inventory',
      users: 'Users',
      allCheckouts: 'Checkout Log',
      myItems: 'My Items',
      inventoryHint: 'Assets, statuses, and actions.',
      usersHint: 'Users and assignments.',
      allCheckoutsHint: 'Admin view for active assignments and closed history.',
      myItemsHint: 'Your current assets and history.',
      login: 'Login',
      register: 'Register',
      activeSession: 'Active session',
      loggedIn: 'Logged in',
      accountMenu: 'Account',
      accountMenuHint: 'Open profile and settings.',
      openUserMenu: 'Open user menu',
      closeUserMenu: 'Close user menu',
      logout: 'Logout',
      profile: 'Profile',
      profileHint: 'Open the signed-in user profile page.',
      settings: 'Settings',
      settingsHint: 'Language and appearance.',
      language: 'Language',
      theme: 'Appearance',
      lightMode: 'Light',
      darkMode: 'Dark',
    },
    auth: {
      loginKicker: 'Secure access',
      loginHeroTitle: 'Pick up where you left off',
      loginHeroText:
        'Sign in to see what is assigned, what is available, and what needs attention.',
      registerKicker: 'Account setup',
      registerHeroTitle: "Let's get started",
      registerHeroText:
        'Create an account so you can sign in and use the parts of the app that belong to you.',
      highlightsInventoryTitle: 'Current statuses',
      highlightsInventoryText: 'You can quickly see what is available, assigned, or in maintenance.',
      highlightsAdminTitle: 'Organized records',
      highlightsAdminText:
        'Assets and assignments are tracked in the same system.',
      highlightsTrackingTitle: 'Personal follow-up',
      highlightsTrackingText: 'Your own items, due dates, and history are easy to open.',
      registerHighlightsWorkspaceTitle: 'Clear interface',
      registerHighlightsWorkspaceText: 'A clear interface for daily work.',
      registerHighlightsNavTitle: 'Quick navigation',
      registerHighlightsNavText: 'The main views are easy to reach.',
      registerHighlightsFeedbackTitle: 'Clear feedback',
      registerHighlightsFeedbackText:
        'Each action returns a clear status and message.',
      welcomeBack: 'Welcome back',
      createAccess: 'New access',
      loginTitle: 'Login',
      registerTitle: 'Register',
      loginText: 'Sign in to continue managing assets and assignments.',
      registerText: 'Create a new account for the asset management app.',
      email: 'Email',
      password: 'Password',
      name: 'Name',
      emailPlaceholder: 'you@company.com',
      passwordPlaceholder: '••••••••',
      minPasswordPlaceholder: 'Minimum 6 characters',
      showPassword: 'Show password',
      hidePassword: 'Hide password',
      fullNamePlaceholder: 'Full name',
      loginSubmit: 'Sign in',
      loginSubmitting: 'Signing in...',
      loginError: 'Sign-in failed.',
      registerSubmit: 'Create account',
      registerSubmitting: 'Registering...',
      invalidEmail: 'Registration requires a valid email address.',
      registerError: 'Registration failed.',
      noAccount: 'No account yet?',
      registerHere: 'Register here.',
      hasAccount: 'Already have an account?',
      loginHere: 'Log in here.',
    },
    inventory: {
      heroKicker: 'Inventory',
      heroTitle: 'Inventory',
      heroText:
        'Company assets and their current status.',
      signal: 'Overview',
      latestRecorded: 'Latest recorded',
      noRecorded: 'No assets recorded yet.',
      total: 'Total assets',
      available: 'Available',
      checkedOut: 'Checked out',
      maintenance: 'Maintenance',
      totalNote: 'Full inventory',
      availableNote: 'Ready to assign',
      checkedOutNote: 'Currently in use',
      maintenanceNote: 'Temporarily unavailable',
      adminKicker: 'Admin controls',
      adminTitle: 'Add new asset',
      adminText:
        'Add a new company asset.',
      liveKicker: 'Inventory',
      liveTitle: 'Active asset list',
      liveText:
        'Review assets, their status, and available actions.',
      emptyTitle: 'No assets in the system yet',
      emptyText:
        'Once the first asset is added, it will appear here.',
      createNamePlaceholder: 'Example: MacBook Pro 16',
      createCategoryPlaceholder: 'Laptop, monitor, peripheral',
      createSerialPlaceholder: 'SN-2026-001',
      createDescriptionPlaceholder: 'Short technical or operational note.',
      image: 'Image',
      imageHint: 'JPG, PNG, or WEBP up to 2 MB.',
      imageSelect: 'Choose image',
      imageReplace: 'Replace image',
      imageRemove: 'Remove image',
      imagePreview: 'Image preview',
      imageInvalidType: 'Only image files can be uploaded.',
      imageTooLarge: 'The image must be 2 MB or smaller.',
      saveItem: 'Save asset',
      saving: 'Saving...',
      details: 'Details',
      edit: 'Edit',
      delete: 'Delete',
      deleting: 'Deleting...',
      makeMaintenance: 'Maintenance',
      makeAvailable: 'Mark available',
      compactDetails: 'Details',
      compactEdit: 'Edit',
      compactDelete: 'Delete',
      compactMaintenance: 'Service',
      compactAvailable: 'Ready',
      assignee: 'Handled by',
      checkedOutBy: 'Checked out by',
      maintenanceBy: 'Moved to maintenance by',
      actorUnknown: 'Unknown user',
      listDescriptionFallback: 'No description provided.',
      editingKicker: 'Editing',
      editingTitle: 'Edit asset',
      editingText: 'Update the asset and save your changes.',
      saveChanges: 'Save changes',
      cancel: 'Cancel',
      category: 'Category',
      recordedAt: 'Recorded',
      serial: 'Serial number',
      description: 'Description',
      name: 'Name',
      createSuccess: 'Asset created successfully.',
      createError: 'Failed to create the asset.',
      updateSuccess: 'Asset updated successfully.',
      updateError: 'Failed to update the asset.',
      deleteSuccess: 'Asset deleted successfully.',
      deleteError: 'Failed to delete the asset.',
      deleteConfirm: 'Are you sure you want to delete this asset?',
      maintenanceSuccess: 'The asset has been moved to maintenance.',
      maintenanceError: 'Failed to move the asset to maintenance.',
      availableSuccess: 'The asset is available again.',
      availableError: 'Failed to mark the asset as available.',
      loadError: 'Failed to load assets.',
      loading: 'Loading assets...',
      searchPlaceholder: 'Search by name, category, or serial number',
      statusFilterLabel: 'Status',
      categoryFilterLabel: 'Category',
      sortByLabel: 'Sort by',
      allStatuses: 'All statuses',
      allCategories: 'All categories',
      sortByName: 'Name',
      sortByNewest: 'Newest first',
      sortByOldest: 'Oldest first',
      noResultsTitle: 'No assets match the current filters',
      noResultsText: 'Try a different search term or a broader filter.',
    },
    checkouts: {
      heroKicker: 'My page',
      heroTitle: 'My Checkouts',
      heroText:
        'Your active assets, due dates, and completed returns.',
      activeState: 'Current state',
      openCount: 'active records',
      overdueSummarySingle: '1 item is already overdue.',
      overdueSummary: (count: number) => `${count} items are already overdue.`,
      noOverdue: 'You have no overdue checkouts right now.',
      active: 'Active',
      overdue: 'Overdue',
      closed: 'Closed',
      activeNote: 'Assets still with you',
      overdueNote: 'Needs immediate attention',
      closedNote: 'Successfully returned items',
      emptyTitle: 'No checkouts yet',
      emptyText:
        'Once you check out an asset, its due date and history will appear here.',
      checkedOutAt: 'Checked out',
      dueAt: 'Due at',
      returnedAt: 'Returned at',
      notClosed: 'Active',
      overdueBadge: 'Overdue',
      overdueAlert: 'This checkout is overdue and the asset should be returned.',
      dueSoonBadge: 'Due soon',
      dueSoonAlert: 'The due date is coming up soon, so plan the return ahead of time.',
      note: 'Note',
      equipmentPage: 'Asset details',
      noNote: 'No note',
      loadError: 'Failed to load your checkouts.',
      loading: 'Loading checkouts...',
      allHeroKicker: 'Checkout log',
      allHeroTitle: 'Checkout activity',
      allHeroText:
        'Active assignments and closed returns.',
      allEmptyTitle: 'There are no checkout records yet',
      allEmptyText:
        'Once the first asset is checked out, the records will appear here.',
      userHeroKicker: 'User',
      userHeroText: (email: string) => `Checkout history for ${email}.`,
      userEmptyTitle: 'This user has no checkout history yet',
      userEmptyText: 'Once an asset is assigned or checked out, the full history will appear here.',
      userLoadError: 'Failed to load this user history.',
      userMissing: 'Missing user identifier.',
      userNotFound: 'User not found.',
      backToAll: 'Back to all checkouts',
      searchPlaceholder: 'Search by asset or serial number',
      allSearchPlaceholder: 'Search by asset, serial number, or user',
      statusFilterLabel: 'State',
      sortByLabel: 'Sort by',
      filterAll: 'All checkouts',
      filterActive: 'Active',
      filterOverdue: 'Overdue',
      filterClosed: 'Closed',
      sortRecent: 'Most recent first',
      sortDueSoon: 'Nearest due date',
      sortDueLate: 'Latest due date',
      noResultsTitle: 'No checkouts match the current filters',
      noResultsText: 'Adjust the search term or change the selected filters.',
    },
    myItems: {
      heroKicker: 'My assets',
      heroTitle: 'My Items',
      heroText:
        'Your current assets and earlier assignments.',
      panelLabel: 'Current use',
      panelValue: 'active items',
      activeLabel: 'Items with you',
      activeNote: 'Assets currently assigned or checked out to you',
      historyLabel: 'History',
      historyNote: 'Previously returned or closed assignments',
      currentKicker: 'Current assets',
      currentTitle: 'Items currently with you',
      currentText: 'The assets you are using right now.',
      currentSearchPlaceholder: 'Search by name, category, or serial number',
      currentEmptyTitle: 'You do not have any active items right now',
      currentEmptyText: 'New assignments will appear here as soon as they are issued to you.',
      historyKicker: 'History',
      historyTitle: 'Previous checkout history',
      historyText: 'Returned and closed records.',
      historySearchPlaceholder: 'Search previous assets and notes',
      historyEmptyTitle: 'No closed history yet',
      historyEmptyText: 'Returned items will appear here later.',
    },
    users: {
      heroKicker: 'Users',
      heroTitle: 'Users',
      heroText: 'Review users and the assets assigned to them.',
      panelLabel: 'Admin focus',
      panelValue: 'users',
      panelText: 'A searchable, sortable list of regular users.',
      totalTracked: 'Total checkouts',
      totalTrackedNote: 'Combined history across all users',
      activeTracked: 'Active assignments',
      activeTrackedNote: 'Currently open assets that are still assigned',
      overdueTracked: 'Overdue assignments',
      overdueTrackedNote: 'Items that need attention soon',
      searchPlaceholder: 'Search by name or email',
      sortLabel: 'Sort by',
      sortByName: 'Name',
      sortByActivity: 'Active assignments',
      emptyTitle: 'There are no users in the system yet',
      emptyText: 'Once the first regular user exists, the full list will appear here.',
      noResultsTitle: 'No users match the current search',
      noResultsText: 'Try another name or email address.',
      userLabel: 'User',
      totalCheckoutsLabel: 'Total checkouts',
      activeCheckoutsLabel: 'Active checkouts',
      overdueCheckoutsLabel: 'Overdue checkouts',
      closedCheckoutsLabel: 'Closed checkouts',
      openOverview: 'Open user',
      backToUsers: 'Back to users',
      detailHeroKicker: 'User record',
      detailHeroText: (email: string) =>
        `Current assets and history for this user: ${email}.`,
      detailPanelValue: 'active items',
      detailPanelText: 'Current assignments and history are shown separately.',
      currentItemsKicker: 'Current assets',
      currentItemsTitle: 'Active assigned assets',
      currentItemsText: 'The assets that are currently assigned to this user.',
      currentSearchPlaceholder: 'Search current assets',
      currentEmptyTitle: 'This user has no active items right now',
      currentEmptyText: 'New assignments will appear here once an asset is issued.',
      historyKicker: 'History',
      historyTitle: 'Closed checkout history',
      historyText: 'Returned and closed records.',
      historySearchPlaceholder: 'Search closed history',
      historyEmptyTitle: 'No closed history yet',
      historyEmptyText: 'The first returned asset will appear here later.',
      loadError: 'Failed to load users.',
      loading: 'Loading users...',
    },
    profile: {
      heroKicker: 'Profile',
      heroText: 'Account details for the signed-in user.',
      panelLabel: 'Role',
      nameLabel: 'Name',
      nameHint: 'The display name of the current signed-in session.',
      emailLabel: 'Email',
      emailHint: 'The email address used to sign in.',
      roleLabel: 'Role',
      roleHint: 'This controls which views and actions are available to you.',
      accountKicker: 'Account',
      accountTitle: 'Core details',
      accountText: 'These are the details of the current signed-in user.',
      quickLinksKicker: 'Links',
      quickLinksTitle: 'Quick actions',
      quickLinksText: 'Shortcuts to the main pages.',
      primaryAdminAction: 'Open users',
      primaryUserAction: 'Open my items',
      settingsAction: 'Open settings',
    },
    settings: {
      heroKicker: 'Settings',
      heroTitle: 'Language and appearance',
      heroText: 'Application language and appearance settings.',
      panelLabel: 'Settings',
      panelValue: '2 options',
      panelText: 'Language is available here, and appearance is prepared here too.',
      languageTitle: 'Language',
      languageText: 'Choose which language the application interface should use.',
      themeTitle: 'Appearance',
      themeText: 'The light and dark mode switch is shown here as a preview.',
    },
    details: {
      back: 'Back to inventory',
      heroKicker: 'Asset record',
      heroText: 'Asset details, status, and history.',
      recorded: 'Recorded',
      totalCheckouts: 'Total checkouts',
      totalCheckoutsNote: 'Complete usage history',
      activeUser: 'Active user',
      free: 'Free',
      notIssued: 'This asset is not currently assigned.',
      deadlinePrefix: 'Deadline',
      dueSoonPrefix: 'Due soon',
      overduePrefix: 'Overdue since',
      lastMovement: 'Last movement',
      noHistory: 'None',
      latestEvent: 'Most recent event',
      noHistoryNote: 'No history yet',
      title: 'Asset record',
      subtitle: 'Core details and current operational status.',
      category: 'Category',
      serial: 'Serial number',
      createdAt: 'Created',
      description: 'Description',
      sendToMaintenance: 'Move to maintenance',
      makeAvailable: 'Mark available',
      checkoutKicker: 'Checkout',
      checkoutTitle: 'Check out asset',
      checkoutText: 'Set the due date and add an optional note.',
      assignTitle: 'Assign asset',
      assignText: 'As an admin, assign this asset to a user.',
      assignUserLabel: 'Assigned user',
      assignSubmit: 'Assign asset',
      assignSuccess: 'Asset assigned successfully.',
      noAssignableUsers: 'No eligible users are available for assignment.',
      dueAt: 'Due at',
      note: 'Note',
      notePlaceholder: 'Optional note',
      checkoutSubmit: 'Check out asset',
      returnKicker: 'Return',
      returnTitle: 'Return asset',
      returnText: 'Close the checkout with a short note if needed.',
      returnSubmit: 'Return asset',
      historyKicker: 'Timeline',
      historyTitle: 'Checkout history',
      historyText: 'All checkout and return records for this asset.',
      noHistoryTitle: 'No history yet',
      noHistoryText: 'There are no checkout records for this asset yet.',
      active: 'Active',
      closed: 'Closed',
      summaryKicker: 'At a glance',
      summaryTitle: 'Summary',
      status: 'Status',
      activeUserLabel: 'Active user',
      unassigned: 'Not assigned',
      openUserHistory: 'Open user profile',
      lastEvent: 'Last event',
      usageKicker: 'Usage guidance',
      usageTitle: 'What to know',
      issueability: 'Checkout availability',
      issueabilityYes: 'Ready to check out',
      issueabilityNo: 'Not available for checkout right now',
      returnability: 'Return eligibility',
      returnabilityYes: 'The open checkout can be closed',
      returnabilityNo: 'There is no open checkout',
      loadError: 'Failed to load asset details.',
      loading: 'Loading asset details...',
      notFound: 'Asset not found.',
      missingId: 'Missing asset identifier.',
      checkoutSuccess: 'Asset checked out successfully.',
      checkoutError: 'Failed to check out the asset.',
      returnSuccess: 'Asset returned successfully.',
      returnError: 'Failed to return the asset.',
      maintenanceSuccess: 'The asset has been moved to maintenance.',
      maintenanceError: 'Failed to move the asset to maintenance.',
      availableSuccess: 'The asset is available again.',
      availableError: 'Failed to mark the asset as available.',
    },
    common: {
      saveInProgress: 'Saving...',
      unknownDate: 'Unknown date',
      unknownDateTime: 'Unknown timestamp',
      me: 'Me',
      search: 'Search',
      view: 'View',
      cardsView: 'Cards',
      listView: 'List',
      asset: 'Asset',
      image: 'Image',
      category: 'Category',
      status: 'Status',
      user: 'User',
      clearFilters: 'Clear filters',
      actions: 'Actions',
      noImage: 'No image',
    },
  },
} as const

type Copy = (typeof copy)[Language]

interface LanguageContextValue {
  language: Language
  setLanguage: (language: Language) => void
  t: Copy
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

interface LanguageProviderProps {
  children: ReactNode
}

function getInitialLanguage(): Language {
  const stored = localStorage.getItem(STORAGE_KEY)
  return stored === 'hu' ? 'hu' : 'en'
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(getInitialLanguage)

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
  }, [language])

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: copy[language],
    }),
    [language],
  )

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)

  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider')
  }

  return context
}
