import {
  createContext,
  useContext,
  useEffect,
  useMemo,
  useState,
  type ReactNode,
} from 'react'

export type Language = 'hu' | 'en'

const STORAGE_KEY = 'asset-management-language'

const copy = {
  hu: {
    brandSubtitle: 'Operations Console',
    nav: {
      inventory: 'Eszközpark',
      myCheckouts: 'Kikéréseim',
      login: 'Bejelentkezés',
      register: 'Regisztráció',
      activeSession: 'Aktív munkamenet',
      loggedIn: 'Bejelentkezve',
      logout: 'Kilépés',
      language: 'Nyelv',
    },
    auth: {
      loginKicker: 'Secure access',
      loginHeroTitle: 'Eszközkezelés, tiszta működéssel.',
      loginHeroText:
        'Jelentkezz be a központi konzolba, ahol az inventory, a kiosztások és az állapotváltások ugyanabban a letisztult felületben élnek.',
      registerKicker: 'Account setup',
      registerHeroTitle: 'Profibb felület, rendezettebb működés.',
      registerHeroText:
        'Hozz létre fiókot, és használd ugyanazt a modern kezelőfelületet inventory kezelésre, kikérésre és admin workflow-kra.',
      highlightsInventoryTitle: 'Átlátható inventory',
      highlightsInventoryText: 'Minden eszköz státusza és adata egy helyen marad.',
      highlightsAdminTitle: 'Gyors admin műveletek',
      highlightsAdminText:
        'Létrehozás, szerkesztés és karbantartásváltás fölösleges zaj nélkül.',
      highlightsTrackingTitle: 'Személyes követhetőség',
      highlightsTrackingText: 'A saját kikérések és határidők azonnal látszanak.',
      registerHighlightsWorkspaceTitle: 'Egységes munkakörnyezet',
      registerHighlightsWorkspaceText:
        'Letisztult felület, erős vizuális hierarchiával.',
      registerHighlightsNavTitle: 'Gyors navigáció',
      registerHighlightsNavText:
        'A legfontosabb nézetek egyetlen felső sávból elérhetők.',
      registerHighlightsFeedbackTitle: 'Azonnali visszajelzés',
      registerHighlightsFeedbackText:
        'Műveletek után világos státuszok és üzenetek segítenek.',
      welcomeBack: 'Welcome back',
      createAccess: 'Create access',
      loginTitle: 'Bejelentkezés',
      registerTitle: 'Regisztráció',
      loginText: 'Lépj be az eszközkezelő konzolba a munkameneted folytatásához.',
      registerText: 'Készíts új hozzáférést az eszközkezelő rendszerhez.',
      email: 'Email',
      password: 'Jelszó',
      name: 'Név',
      emailPlaceholder: 'te@ceg.hu',
      passwordPlaceholder: '••••••••',
      minPasswordPlaceholder: 'Minimum 6 karakter',
      fullNamePlaceholder: 'Teljes név',
      loginSubmit: 'Belépés',
      loginSubmitting: 'Beléptetés...',
      registerSubmit: 'Fiók létrehozása',
      registerSubmitting: 'Regisztrálás...',
      noAccount: 'Még nincs fiókod?',
      registerHere: 'Regisztrálj itt',
      hasAccount: 'Már van fiókod?',
      loginHere: 'Lépj be innen',
    },
    inventory: {
      heroKicker: 'Inventory overview',
      heroTitle: 'Eszközpark',
      heroText:
        'A teljes eszközállomány, státuszok és admin műveletek egy rendezett, professzionális nézetben.',
      signal: 'Rendszerjel',
      latestRecorded: 'Legutóbb rögzítve',
      noRecorded: 'Még nincs rögzített eszköz.',
      total: 'Összes eszköz',
      available: 'Elérhető',
      checkedOut: 'Kikérve',
      maintenance: 'Karbantartás',
      totalNote: 'Teljes inventory',
      availableNote: 'Azonnal kiadható',
      checkedOutNote: 'Aktív használatban',
      maintenanceNote: 'Ideiglenesen zárolva',
      adminKicker: 'Admin controls',
      adminTitle: 'Új eszköz rögzítése',
      adminText:
        'Gyors admin űrlap laptopok, monitorok és egyéb eszközök felvételéhez.',
      liveKicker: 'Live inventory',
      liveTitle: 'Aktív eszközlista',
      liveText:
        'Minden eszköz azonnal áttekinthető státusszal, metaadatokkal és gyors műveletekkel.',
      emptyTitle: 'Még nincs eszköz a rendszerben',
      emptyText:
        'Az első rögzített eszköz után itt már egy rendezett, profi inventory nézet fog megjelenni.',
      createNamePlaceholder: 'Pl. MacBook Pro 16',
      createCategoryPlaceholder: 'Laptop, monitor, periféria',
      createSerialPlaceholder: 'SN-2026-001',
      createDescriptionPlaceholder: 'Rövid műszaki vagy üzemeltetési megjegyzés.',
      saveItem: 'Eszköz mentése',
      saving: 'Mentés...',
      details: 'Részletek',
      edit: 'Szerkesztés',
      delete: 'Törlés',
      deleting: 'Törlés...',
      makeMaintenance: 'Karbantartás',
      makeAvailable: 'Elérhetővé tesz',
      editingKicker: 'Editing',
      editingTitle: 'Eszköz szerkesztése',
      editingText:
        'Módosítsd a nyilvántartási adatokat és mentsd el a változásokat.',
      saveChanges: 'Változások mentése',
      cancel: 'Mégse',
      category: 'Kategória',
      recordedAt: 'Rögzítve',
      serial: 'Gyári szám',
      description: 'Leírás',
      name: 'Név',
      createSuccess: 'Az eszköz sikeresen létrehozva.',
      createError: 'Nem sikerült létrehozni az eszközt.',
      updateSuccess: 'Az eszköz sikeresen frissítve.',
      updateError: 'Nem sikerült frissíteni az eszközt.',
      deleteSuccess: 'Az eszköz sikeresen törölve.',
      deleteError: 'Nem sikerült törölni az eszközt.',
      deleteConfirm: 'Biztosan törölni szeretnéd ezt az eszközt?',
      maintenanceSuccess: 'Az eszköz karbantartás alá helyezve.',
      maintenanceError: 'Nem sikerült karbantartás alá helyezni az eszközt.',
      availableSuccess: 'Az eszköz ismét elérhető.',
      availableError: 'Nem sikerült elérhetővé tenni az eszközt.',
      loadError: 'Nem sikerült betölteni az eszközöket.',
      loading: 'Eszközök betöltése...',
    },
    checkouts: {
      heroKicker: 'Personal workspace',
      heroTitle: 'Saját kikérések',
      heroText:
        'Az aktív eszközeid, határidők és lezárt visszahozások egy tiszta, átlátható nézetben.',
      activeState: 'Aktív állapot',
      openCount: 'nyitott kikérés',
      overdueSummarySingle: '1 tétel már lejárt határidejű.',
      overdueSummary: (count: number) => `${count} tétel már lejárt határidejű.`,
      noOverdue: 'Jelenleg nincs lejárt kikérésed.',
      active: 'Aktív',
      overdue: 'Lejárt',
      closed: 'Lezárt',
      activeNote: 'Még vissza nem hozott eszközök',
      overdueNote: 'Azonnali figyelmet igényel',
      closedNote: 'Sikeresen visszahozott tételek',
      emptyTitle: 'Még nincs kikérésed',
      emptyText:
        'Ha kikérsz egy eszközt, itt rögtön látni fogod a határidőt és az előzményeket is.',
      checkedOutAt: 'Kikérve',
      dueAt: 'Határidő',
      returnedAt: 'Visszahozva',
      notClosed: 'Még nincs lezárva',
      overdueBadge: 'Lejárt',
      overdueAlert: 'Ez a kikérés lejárt, az eszközt vissza kell hozni.',
      note: 'Megjegyzés',
      equipmentPage: 'Eszköz adatlap',
      loadError: 'Nem sikerült betölteni a kikéréseidet.',
      loading: 'Kikérések betöltése...',
    },
    details: {
      back: 'Vissza az eszközparkhoz',
      heroKicker: 'Equipment record',
      heroText: 'részletes állapot, kikérési előzmények és gyors műveletek.',
      recorded: 'Rögzítve',
      totalCheckouts: 'Összes kikérés',
      totalCheckoutsNote: 'Teljes használati előzmény',
      activeUser: 'Aktív használó',
      free: 'Szabad',
      notIssued: 'Az eszköz jelenleg nincs kiadva.',
      deadlinePrefix: 'Határidő',
      lastMovement: 'Utolsó mozgás',
      noHistory: 'Nincs',
      latestEvent: 'Legutóbbi kikérési esemény',
      noHistoryNote: 'Még nincs előzmény',
      title: 'Eszköz adatlap',
      subtitle: 'Főbb metaadatok és aktuális üzemeltetési állapot.',
      category: 'Kategória',
      serial: 'Gyári szám',
      createdAt: 'Létrehozva',
      description: 'Leírás',
      sendToMaintenance: 'Karbantartás alá helyezés',
      makeAvailable: 'Elérhetővé tesz',
      checkoutKicker: 'Checkout',
      checkoutTitle: 'Eszköz kikérése',
      checkoutText: 'Add meg a határidőt és opcionális megjegyzést az átvételhez.',
      dueAt: 'Határidő',
      note: 'Megjegyzés',
      notePlaceholder: 'Opcionális megjegyzés',
      checkoutSubmit: 'Kikérem az eszközt',
      returnKicker: 'Return flow',
      returnTitle: 'Eszköz visszahozása',
      returnText: 'Zárd le a kikérést egy rövid megjegyzéssel, ha szükséges.',
      returnSubmit: 'Visszahozom az eszközt',
      historyKicker: 'Timeline',
      historyTitle: 'Kikérési előzmények',
      historyText: 'Minden eddigi mozgás és használói esemény egy helyen.',
      noHistoryTitle: 'Még nincs előzmény',
      noHistoryText: 'Ehhez az eszközhöz még nem tartozik egyetlen kikérés sem.',
      active: 'Aktív',
      closed: 'Lezárt',
      summaryKicker: 'Quick facts',
      summaryTitle: 'Összefoglaló',
      status: 'Státusz',
      activeUserLabel: 'Aktív használó',
      unassigned: 'Nincs kiosztva',
      lastEvent: 'Utolsó esemény',
      usageKicker: 'Usage notes',
      usageTitle: 'Mire figyelj',
      issueability: 'Kiadhatóság',
      issueabilityYes: 'Azonnal kiadható',
      issueabilityNo: 'Jelenleg nem adható ki',
      returnability: 'Visszavétel',
      returnabilityYes: 'Aktív kikérés lezárható',
      returnabilityNo: 'Nincs nyitott kikérés',
      loadError: 'Nem sikerült betölteni az eszköz részleteit.',
      loading: 'Eszköz adatlap betöltése...',
      notFound: 'Az eszköz nem található.',
      missingId: 'Hiányzó eszközazonosító.',
      checkoutSuccess: 'Az eszköz sikeresen kikérve.',
      checkoutError: 'Nem sikerült kikérni az eszközt.',
      returnSuccess: 'Az eszköz sikeresen visszahozva.',
      returnError: 'Nem sikerült visszahozni az eszközt.',
      maintenanceSuccess: 'Az eszköz karbantartás alá helyezve.',
      maintenanceError: 'Nem sikerült karbantartás alá helyezni az eszközt.',
      availableSuccess: 'Az eszköz ismét elérhető.',
      availableError: 'Nem sikerült elérhetővé tenni az eszközt.',
    },
    common: {
      saveInProgress: 'Mentés...',
      unknownDate: 'Ismeretlen dátum',
      unknownDateTime: 'Ismeretlen időpont',
    },
  },
  en: {
    brandSubtitle: 'Operations Console',
    nav: {
      inventory: 'Inventory',
      myCheckouts: 'My Checkouts',
      login: 'Login',
      register: 'Register',
      activeSession: 'Active session',
      loggedIn: 'Logged in',
      logout: 'Logout',
      language: 'Language',
    },
    auth: {
      loginKicker: 'Secure access',
      loginHeroTitle: 'Asset control, made clearer.',
      loginHeroText:
        'Sign in to the central console where inventory, assignments, and status changes live in one focused interface.',
      registerKicker: 'Account setup',
      registerHeroTitle: 'Sharper interface, smoother workflow.',
      registerHeroText:
        'Create an account and use the same modern workspace for inventory, checkout flows, and admin actions.',
      highlightsInventoryTitle: 'Transparent inventory',
      highlightsInventoryText: 'Every asset status and detail stays visible in one place.',
      highlightsAdminTitle: 'Fast admin actions',
      highlightsAdminText:
        'Create, edit, and switch maintenance state without extra UI noise.',
      highlightsTrackingTitle: 'Personal visibility',
      highlightsTrackingText: 'Your own checkouts and deadlines stay easy to track.',
      registerHighlightsWorkspaceTitle: 'Unified workspace',
      registerHighlightsWorkspaceText:
        'A clean interface with strong visual hierarchy and less clutter.',
      registerHighlightsNavTitle: 'Quick navigation',
      registerHighlightsNavText: 'The most important views stay one click away.',
      registerHighlightsFeedbackTitle: 'Immediate feedback',
      registerHighlightsFeedbackText:
        'Clear messages and states support each operation.',
      welcomeBack: 'Welcome back',
      createAccess: 'Create access',
      loginTitle: 'Login',
      registerTitle: 'Register',
      loginText: 'Sign in to continue your asset management session.',
      registerText: 'Create a new account for the asset management system.',
      email: 'Email',
      password: 'Password',
      name: 'Name',
      emailPlaceholder: 'you@company.com',
      passwordPlaceholder: '••••••••',
      minPasswordPlaceholder: 'Minimum 6 characters',
      fullNamePlaceholder: 'Full name',
      loginSubmit: 'Sign in',
      loginSubmitting: 'Signing in...',
      registerSubmit: 'Create account',
      registerSubmitting: 'Registering...',
      noAccount: 'No account yet?',
      registerHere: 'Register here',
      hasAccount: 'Already have an account?',
      loginHere: 'Log in here',
    },
    inventory: {
      heroKicker: 'Inventory overview',
      heroTitle: 'Inventory',
      heroText:
        'The full asset inventory, status overview, and admin actions in one structured workspace.',
      signal: 'System signal',
      latestRecorded: 'Latest recorded',
      noRecorded: 'No assets recorded yet.',
      total: 'Total assets',
      available: 'Available',
      checkedOut: 'Checked out',
      maintenance: 'Maintenance',
      totalNote: 'Full inventory',
      availableNote: 'Ready to assign',
      checkedOutNote: 'Currently in use',
      maintenanceNote: 'Temporarily unavailable',
      adminKicker: 'Admin controls',
      adminTitle: 'Add new asset',
      adminText:
        'A fast admin form for laptops, monitors, and other company assets.',
      liveKicker: 'Live inventory',
      liveTitle: 'Active asset list',
      liveText:
        'Every asset is easy to review with status, metadata, and quick actions.',
      emptyTitle: 'No assets in the system yet',
      emptyText:
        'Once the first asset is recorded, a cleaner inventory overview will appear here.',
      createNamePlaceholder: 'Example: MacBook Pro 16',
      createCategoryPlaceholder: 'Laptop, monitor, peripheral',
      createSerialPlaceholder: 'SN-2026-001',
      createDescriptionPlaceholder: 'Short technical or operational note.',
      saveItem: 'Save asset',
      saving: 'Saving...',
      details: 'Details',
      edit: 'Edit',
      delete: 'Delete',
      deleting: 'Deleting...',
      makeMaintenance: 'Maintenance',
      makeAvailable: 'Mark available',
      editingKicker: 'Editing',
      editingTitle: 'Edit asset',
      editingText: 'Update the record and save the changes.',
      saveChanges: 'Save changes',
      cancel: 'Cancel',
      category: 'Category',
      recordedAt: 'Recorded',
      serial: 'Serial number',
      description: 'Description',
      name: 'Name',
      createSuccess: 'Asset created successfully.',
      createError: 'Failed to create the asset.',
      updateSuccess: 'Asset updated successfully.',
      updateError: 'Failed to update the asset.',
      deleteSuccess: 'Asset deleted successfully.',
      deleteError: 'Failed to delete the asset.',
      deleteConfirm: 'Are you sure you want to delete this asset?',
      maintenanceSuccess: 'The asset has been moved to maintenance.',
      maintenanceError: 'Failed to move the asset to maintenance.',
      availableSuccess: 'The asset is available again.',
      availableError: 'Failed to mark the asset as available.',
      loadError: 'Failed to load assets.',
      loading: 'Loading assets...',
    },
    checkouts: {
      heroKicker: 'Personal workspace',
      heroTitle: 'My Checkouts',
      heroText:
        'Your active assets, deadlines, and completed returns in one clearer view.',
      activeState: 'Current state',
      openCount: 'open checkouts',
      overdueSummarySingle: '1 item is already overdue.',
      overdueSummary: (count: number) => `${count} items are already overdue.`,
      noOverdue: 'You have no overdue checkouts right now.',
      active: 'Active',
      overdue: 'Overdue',
      closed: 'Closed',
      activeNote: 'Items not returned yet',
      overdueNote: 'Needs immediate attention',
      closedNote: 'Successfully returned items',
      emptyTitle: 'You do not have any checkouts yet',
      emptyText:
        'Once you check out an item, its deadline and history will appear here right away.',
      checkedOutAt: 'Checked out',
      dueAt: 'Due at',
      returnedAt: 'Returned at',
      notClosed: 'Not closed yet',
      overdueBadge: 'Overdue',
      overdueAlert: 'This checkout is overdue and the asset should be returned.',
      note: 'Note',
      equipmentPage: 'Asset page',
      loadError: 'Failed to load your checkouts.',
      loading: 'Loading checkouts...',
    },
    details: {
      back: 'Back to inventory',
      heroKicker: 'Equipment record',
      heroText: 'detailed status, checkout history, and quick actions.',
      recorded: 'Recorded',
      totalCheckouts: 'Total checkouts',
      totalCheckoutsNote: 'Full usage history',
      activeUser: 'Active user',
      free: 'Free',
      notIssued: 'This asset is not currently assigned.',
      deadlinePrefix: 'Deadline',
      lastMovement: 'Last movement',
      noHistory: 'None',
      latestEvent: 'Latest checkout event',
      noHistoryNote: 'No history yet',
      title: 'Asset record',
      subtitle: 'Core metadata and current operational status.',
      category: 'Category',
      serial: 'Serial number',
      createdAt: 'Created',
      description: 'Description',
      sendToMaintenance: 'Move to maintenance',
      makeAvailable: 'Mark available',
      checkoutKicker: 'Checkout',
      checkoutTitle: 'Check out asset',
      checkoutText: 'Set the deadline and an optional note for handover.',
      dueAt: 'Due at',
      note: 'Note',
      notePlaceholder: 'Optional note',
      checkoutSubmit: 'Check out asset',
      returnKicker: 'Return flow',
      returnTitle: 'Return asset',
      returnText: 'Close the checkout with a short note if needed.',
      returnSubmit: 'Return asset',
      historyKicker: 'Timeline',
      historyTitle: 'Checkout history',
      historyText: 'Every movement and usage event in one place.',
      noHistoryTitle: 'No history yet',
      noHistoryText: 'There are no checkout records for this asset yet.',
      active: 'Active',
      closed: 'Closed',
      summaryKicker: 'Quick facts',
      summaryTitle: 'Summary',
      status: 'Status',
      activeUserLabel: 'Active user',
      unassigned: 'Not assigned',
      lastEvent: 'Last event',
      usageKicker: 'Usage notes',
      usageTitle: 'What to watch',
      issueability: 'Availability',
      issueabilityYes: 'Ready to assign now',
      issueabilityNo: 'Not available for checkout right now',
      returnability: 'Return state',
      returnabilityYes: 'Open checkout can be closed',
      returnabilityNo: 'There is no open checkout',
      loadError: 'Failed to load asset details.',
      loading: 'Loading asset details...',
      notFound: 'Asset not found.',
      missingId: 'Missing asset identifier.',
      checkoutSuccess: 'Asset checked out successfully.',
      checkoutError: 'Failed to check out the asset.',
      returnSuccess: 'Asset returned successfully.',
      returnError: 'Failed to return the asset.',
      maintenanceSuccess: 'The asset has been moved to maintenance.',
      maintenanceError: 'Failed to move the asset to maintenance.',
      availableSuccess: 'The asset is available again.',
      availableError: 'Failed to mark the asset as available.',
    },
    common: {
      saveInProgress: 'Saving...',
      unknownDate: 'Unknown date',
      unknownDateTime: 'Unknown timestamp',
    },
  },
} as const

type Copy = (typeof copy)[Language]

interface LanguageContextValue {
  language: Language
  setLanguage: (language: Language) => void
  t: Copy
}

const LanguageContext = createContext<LanguageContextValue | undefined>(undefined)

interface LanguageProviderProps {
  children: ReactNode
}

function getInitialLanguage(): Language {
  const stored = localStorage.getItem(STORAGE_KEY)
  return stored === 'en' ? 'en' : 'hu'
}

export function LanguageProvider({ children }: LanguageProviderProps) {
  const [language, setLanguage] = useState<Language>(getInitialLanguage)

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
  }, [language])

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      t: copy[language],
    }),
    [language],
  )

  return (
    <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)

  if (!context) {
    throw new Error('useLanguage must be used inside LanguageProvider')
  }

  return context
}
